module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.coffee = [
    'AFFOGATO',
    'AMERICANO',
    'CAFFÈ LATTE',
    'Pond',
    'CAFFÈ MOCHA',
    'BREW',
    'Ghost  ESPRESSO',
    'FLAT WHITE',
    'Dispersed  ESPRESSO',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'FRAPPÉ',
    'FREAKSHAKE',
    'Cliffs',
    'Hollow'
]
